# Generated by Django 5.0.6 on 2024-06-28 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('nome', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(max_length=40)),
                ('duracao', models.CharField(max_length=30)),
                ('caminho_treino_img', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(default='Treino', max_length=30)),
                ('caminho_treino_url', models.CharField(default='nome_treino', max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('repeticoes', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='ballers085.treinos')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treinos',
            name='criador',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='ballers085.userprofile'),
        ),
    ]
