# Generated by Django 5.0.6 on 2024-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballers085', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link_foto_perfil',
            field=models.CharField(default='user-icon.jpg', max_length=100),
        ),
    ]
