# Generated by Django 5.0.6 on 2024-06-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballers085', '0002_userprofile_link_foto_perfil'),
    ]

    operations = [
    migrations.RunSQL(
        "DROP TABLE IF EXISTS django_session",
        reverse_sql="CREATE TABLE django_session (session_key varchar(40) NOT NULL PRIMARY KEY, session_data text NOT NULL, expire_date datetime NOT NULL)"
    ),
    ]