# Generated by Django 5.0 on 2024-07-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballers085', '0003_auto_20240629_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='link_foto_perfil',
            field=models.CharField(default='imgs/usuarios/user-icon.jpg', max_length=100),
        ),
    ]
