# Generated by Django 5.0 on 2024-07-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballers085', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinos',
            name='caminho_treino_img',
        ),
        migrations.AddField(
            model_name='treinos',
            name='link_video_treino',
            field=models.CharField(default='RpC7sv8_LIg', max_length=50),
        ),
    ]
